[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
call_target = "82UAtJWsPJvmD6JV1Z3bpL4Nr6TD7gQrZNN9K3HMygV6"
simple_router = "3QSSxzUPrct8Go38smbPdb8Lo8WnRNyFa6owKnCaYbuW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
